### ISSUE TITLE
"code": "ERR_HTTP_INVALID_HEADER_VALUE" when get request run in parallel

### ISSUE THREAD

**Issue by spatchamatla** [pactumjs/pactum#317]
**Describe the bug**
when running tests in parallel, pactum js throws multiple console errors..`Error performing request` and ` "code": "ERR_HTTP_INVALID_HEADER_VALUE"` . on retries it works fine

```
  console.error
    Error performing request

      at ../../node_modules/pactum/src/adapters/logger.js:26:24
          at Array.forEach (<anonymous>)
      at Object.error (../../node_modules/pactum/src/adapters/logger.js:26:7)
      at Logger.error (../../node_modules/pactum/src/plugins/logger.js:84:20)
      at getResponse (../../node_modules/pactum/src/models/Tosser.js:267:11)
      at Tosser.setResponse (../../node_modules/pactum/src/models/Tosser.js:76:21)
      at Tosser.toss (../../node_modules/pactum/src/models/Tosser.js:35:7)

  console.error
    {
      "code": "ERR_HTTP_INVALID_HEADER_VALUE"
    }

      at ../../node_modules/pactum/src/adapters/logger.js:26:24
          at Array.forEach (<anonymous>)
      at Object.error (../../node_modules/pactum/src/adapters/logger.js:26:7)
      at Logger.error (../../node_modules/pactum/src/plugins/logger.js:84:20)
      at getResponse (../../node_modules/pactum/src/models/Tosser.js:267:11)
      at Tosser.setResponse (../../node_modules/pactum/src/models/Tosser.js:76:21)
      at Tosser.toss (../../node_modules/pactum/src/models/Tosser.js:35:7)

```

**To Reproduce**
1. Run get request (50 requests) in parallel using Jest `it.concurrent.each()`
2. See error

**Expected behavior**
no error thrown on parallel runs

**Software (please complete the following information):**
 - OS: macOS 14.3
 - NodeJS Version : v18.19.0
 - Test Runner : Jest v29.7.0
 - pactum: v3.6.0

**Comment by ASaiAnudeep** [comment]
Hey @spatchamatla , could you please share the [debug logs](https://pactumjs.github.io/api/settings/setLogLevel.html#setloglevel) here.
