### ISSUE TITLE
Interaction not exercised: GET

### ISSUE THREAD

**Issue by JyotiPMallick** [pactumjs/pactum#364]
Trying to implement the Contract test using Pactum, here is my sample code,

```js
const { reporter, flow, mock, handler } = require("pactum");
const pf = require("pactum-flow-plugin");
const jwtTokenHandler = require("./jwtTokenHandler");
let bearerTOKEN;

function addFlowReporter() {
  pf.config.url = "http://localhost:8080";
  pf.config.projectId = "Order-Service";
  pf.config.projectName = "[T01] Order-Service";
  pf.config.version = "1.0.0";
  pf.config.username = "*****";
  pf.config.password = "*****";
  reporter.add(pf.reporter);
}

// global before
before(async () => {
  addFlowReporter();
  await mock.start(4000);
  bearerAccessToken = await jwtTokenHandler.generateBearerToken();
});

// global after
after(async () => {
  await mock.stop();
  await reporter.end();
});

handler.addInteractionHandler("Fetch the orders for a given lead", () => {
  return {
    provider: "Node API", // same as provider project
    flow: "fetch the order for lead id", // same as provider flow name
    request: {
      method: "GET",
      path: "https://<test_server>/api/order?leadId=434",
      withBearerToken: `${bearerAccessToken}`,
    },
    response: {
      status: 200,
      body: {
        responseCode: 200,
        message: "Success!",
        data: [[]],
      },
    },
  };
});

it("Post Orders to Order_Service", async () => {
  await flow("Post an order for a lead")
    .useInteraction("Fetch the orders for the Lead_Id")
    .post("https://<test_server>/api/order")
    .withHeaders("Content-Type", "application/json")
    .withBearerToken(bearerAccessToken)
    .withJson({
      orderDate: "2024-08-02 00:00:00",
      maturityDate: "2024-08-29 00:00:00",
      transactionAmount: 1000,
      leadID: 434,
      orderStatusTypeID: 10,
      loanTypeID: 2,
      applicationNumber: "string",
      approvedAmount: 500,
      isFileSubmissionDone:
      studentProfileId: 1,
    });
});

```

I am getting the following error, 

```js
[I] Mock server is listening on http://0.0.0.0:4000
[W] Interaction Not Exercised
{
  "method": "GET",
  "path": "https://<test_server>/api/order?leadId=434"
}
[W] Request
{
  "url": "https://<test_server>/api/order",
  "method": "POST",
  "headers": {
    "Content-Type": "application/json",
    "Authorization": "Bearer <bearerAccessToken>"
  },
  "path": "/api/order",
  "body": {
    orderDate: "2024-08-02 00:00:00",
      maturityDate: "2024-08-29 00:00:00",
      transactionAmount: 1000,
      leadID: 434,
      orderStatusTypeID: 10,
      loanTypeID: 2,
      applicationNumber: "string",
      approvedAmount: 500,
      isFileSubmissionDone:
      studentProfileId: 1
  },
  "timeout": 3000
}
[W] Response
{
  "statusCode": 200,
  "headers": {
    "content-length": "53",
    "content-type": "application/json; charset=utf-8",
    "date": "Thu, 04 Jul 2024 06:11:10 GMT",
    "access-control-allow-origin": "*",
    "etag": "W/\"35-nYRf1SCdO02PSh/SneMK1h340bA\"",
    "x-powered-by": "Express"
  },
  "body": {
    "responseCode": 200,
    "message": "Success!",
    "data": true
  }
}
  1) Post Orders to B2B Order Service
[I] Mock server stopped on port 4000

Publishing "Order-Service" with version "1.0.0"

Creating Project
Creating Analysis
Uploading Interactions
Uploading Flows
Processing Analysis

  0 passing (1s)
  1 failing

  1) Post Orders to B2B Order Service:
     AssertionError [ERR_ASSERTION]: Interaction not exercised: GET - https://<test_server>/api/order?leadId=434
      at Expect.fail (node_modules\pactum\src\models\expect.js:461:12)
      at Expect.validateInteractions (node_modules\pactum\src\models\expect.js:88:14)
      at Tosser.validateNonBackgroundInteractions (node_modules\pactum\src\models\Tosser.js:234:17)
      at Tosser.validate (node_modules\pactum\src\models\Tosser.js:209:12)
      at Tosser.toss (node_modules\pactum\src\models\Tosser.js:46:18)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by ASaiAnudeep** [comment]
In Interaction handler `path` should be relative..
```js
handler.addInteractionHandler("Fetch the orders for a given lead", () => {
  return {
    provider: "Node API", // same as provider project
    flow: "fetch the order for lead id", // same as provider flow name
    request: {
      method: "GET",
      path: "/api/order?leadId=434",
      withBearerToken: `${bearerAccessToken}`,
    },
    response: {
      status: 200,
      body: {
        responseCode: 200,
        message: "Success!",
        data: [[]],
      },
    },
  };
});

**Comment by JyotiPMallick** [comment]
@ASaiAnudeep thank you for prompt answer, but when I changed and rerun I am getting 

```
[W] Interaction Not Exercised
{
  "method": "GET",
  "path": "/api/order?leadId=434"
}
[W] Request
{
  "url": "https://<test_server>/api/order",
  "method": "POST",
  "headers": {
    "Content-Type": "application/json",
    "Authorization": "Bearer <bearerAccessToken>"
  },
  "path": "/api/order",
  "body": {
    orderDate: "2024-08-02 00:00:00",
      maturityDate: "2024-08-29 00:00:00",
      transactionAmount: 1000,
      leadID: 434,
      orderStatusTypeID: 10,
      loanTypeID: 2,
      applicationNumber: "string",
      approvedAmount: 500,
      isFileSubmissionDone:
      studentProfileId: 1
  },
  "timeout": 3000
}
[W] Response
{
  "statusCode": 200,
  "headers": {
    "content-length": "53",
    "content-type": "application/json; charset=utf-8",
    "date": "Thu, 04 Jul 2024 08:25:42 GMT",
    "access-control-allow-origin": "*",
    "etag": "W/\"35-nYRf1SCdO02PSh/SneMK1h340bA\"",
    "x-powered-by": "Express"
  },
  "body": {
    "responseCode": 200,
    "message": "Success!",
    "data": true
  }
}
  1) Post Orders to B2B Order Service
[I] Mock server stopped on port 4000

Publishing "Order-Service" with version "1.0.1"

Creating Project
Creating Analysis
  2) "after all" hook for "Post Orders to B2B Order Service"

  0 passing (3s)
  2 failing

  1) Post Orders to B2B Order Service:
     AssertionError [ERR_ASSERTION]: Interaction not exercised: GET - /api/order?leadId=434
      at Expect.fail (node_modules\pactum\src\models\expect.js:461:12)
      at Expect.validateInteractions (node_modules\pactum\src\models\expect.js:88:14)
      at Tosser.validateNonBackgroundInteractions (node_modules\pactum\src\models\Tosser.js:234:17)
      at Tosser.validate (node_modules\pactum\src\models\Tosser.js:209:12)
      at Tosser.toss (node_modules\pactum\src\models\Tosser.js:46:18)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

  2) "after all" hook for "Post Orders to B2B Order Service":
     StatusCodeError: 400 - {"error":"Analysis already exists"}
      at Object.reject (node_modules\phin-retry\src\index.js:184:11)
      at Object.__fetch (node_modules\phin-retry\src\index.js:268:21)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async createAnalysis (node_modules\pactum-flow-plugin\src\publisher.js:29:15)
      at async publish (node_modules\pactum-flow-plugin\src\publisher.js:116:16)
      at async run (node_modules\pactum-flow-plugin\src\runner.js:12:3)
      at async Object.end (node_modules\pactum-flow-plugin\src\reporter.js:13:3)
      at async Object.end (node_modules\pactum\src\exports\reporter.js:32:23)
      at async Context.<anonymous> (test\contract\order.contract.spec.js:31:3)

```
